# Generated by Django 4.0 on 2021-12-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_tag_article_category_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=0),
        ),
    ]
